---
platform: linux

image_resource:
  type: docker-image
  source: {repository: golang}

inputs:
- name: docs
- name: version

outputs:
- name: built-docs

params:
  ANALYTICS_ID:

run:
  path: docs/ci/build-docs
